import type { NewProduct } from '@/db/schema';

/**
 * Справочник блюд казахской и центральноазиатской кухни.
 *
 * ⚠️ ТРЕБУЕТ ПРОВЕРКИ ПЕРЕД ПРОДАКШЕНОМ.
 *
 * Значения ниже — расчётные оценки по типовым рецептурам, а не лабораторные
 * измерения. Их порядок величины верен, но конкретная цифра может расходиться
 * с реальностью на 15–25%: жирность мяса, доля теста и количество масла
 * различаются от рецепта к рецепту сильнее, чем в стандартизованных продуктах.
 *
 * Поэтому все записи помечены isVerified: false — в поиске они показываются
 * ниже проверенных, а в интерфейсе к ним стоит выводить оговорку про оценку.
 *
 * Как довести до продакшена, в порядке убывания надёжности:
 *  1. Сборник рецептур и таблицы химического состава блюд (Скурихин)
 *     либо аналогичный официальный источник;
 *  2. Пересчёт от сырья: разложить рецепт на ингредиенты из USDA и посчитать
 *     с учётом потерь при готовке;
 *  3. Лабораторный анализ — если продукт вырастет до масштабов, где это окупится.
 *
 * После проверки записи ставится isVerified: true.
 */
export const KAZAKH_FOODS: NewProduct[] = [
  /* ─────────────────────── Мясные блюда ─────────────────────── */
  {
    nameRu: 'Бешбармак',
    nameKk: 'Бесбармақ',
    nameEn: 'beshbarmak',
    source: 'local',
    externalId: 'kz-beshbarmak',
    kcalPer100g: 218,
    proteinPer100g: 12.4,
    fatPer100g: 12.1,
    carbsPer100g: 15.8,
    defaultPortionG: 350,
    portionLabelRu: 'порция',
    portionLabelKk: 'бір порция',
    isVerified: false,
  },
  {
    nameRu: 'Куырдак',
    nameKk: 'Қуырдақ',
    nameEn: 'kuyrdak',
    source: 'local',
    externalId: 'kz-kuyrdak',
    kcalPer100g: 232,
    proteinPer100g: 15.2,
    fatPer100g: 17.4,
    carbsPer100g: 4.6,
    defaultPortionG: 250,
    portionLabelRu: 'порция',
    portionLabelKk: 'бір порция',
    isVerified: false,
  },
  {
    nameRu: 'Казы (конская колбаса)',
    nameKk: 'Қазы',
    nameEn: 'kazy horse sausage',
    source: 'local',
    externalId: 'kz-kazy',
    kcalPer100g: 385,
    proteinPer100g: 12.0,
    fatPer100g: 37.5,
    carbsPer100g: 0,
    defaultPortionG: 60,
    portionLabelRu: 'несколько ломтиков',
    portionLabelKk: 'бірнеше тілім',
    isVerified: false,
  },
  {
    nameRu: 'Шужык',
    nameKk: 'Шұжық',
    nameEn: 'shuzhyk sausage',
    source: 'local',
    externalId: 'kz-shuzhyk',
    kcalPer100g: 378,
    proteinPer100g: 14.5,
    fatPer100g: 35.8,
    carbsPer100g: 0,
    defaultPortionG: 60,
    portionLabelRu: 'несколько ломтиков',
    portionLabelKk: 'бірнеше тілім',
    isVerified: false,
  },
  {
    nameRu: 'Сорпа (мясной бульон)',
    nameKk: 'Сорпа',
    nameEn: 'sorpa meat broth',
    source: 'local',
    externalId: 'kz-sorpa',
    kcalPer100g: 42,
    proteinPer100g: 3.1,
    fatPer100g: 2.8,
    carbsPer100g: 1.2,
    defaultPortionG: 300,
    portionLabelRu: 'пиала',
    portionLabelKk: 'кесе',
    isVerified: false,
  },
  {
    nameRu: 'Асып',
    nameKk: 'Асып',
    nameEn: 'asyp',
    source: 'local',
    externalId: 'kz-asyp',
    kcalPer100g: 268,
    proteinPer100g: 11.8,
    fatPer100g: 18.6,
    carbsPer100g: 13.4,
    defaultPortionG: 150,
    portionLabelRu: 'порция',
    isVerified: false,
  },

  /* ─────────────────── Тесто и выпечка ──────────────────────── */
  {
    nameRu: 'Баурсак',
    nameKk: 'Бауырсақ',
    nameEn: 'baursak fried dough',
    source: 'local',
    externalId: 'kz-baursak',
    kcalPer100g: 352,
    proteinPer100g: 6.8,
    fatPer100g: 15.2,
    carbsPer100g: 46.8,
    defaultPortionG: 20,
    portionLabelRu: 'штука',
    portionLabelKk: 'дана',
    isVerified: false,
  },
  {
    nameRu: 'Шелпек',
    nameKk: 'Шелпек',
    nameEn: 'shelpek flatbread',
    source: 'local',
    externalId: 'kz-shelpek',
    kcalPer100g: 328,
    proteinPer100g: 7.2,
    fatPer100g: 13.8,
    carbsPer100g: 44.5,
    defaultPortionG: 60,
    portionLabelRu: 'лепёшка',
    portionLabelKk: 'нан',
    isVerified: false,
  },
  {
    nameRu: 'Манты',
    nameKk: 'Манты',
    nameEn: 'manty steamed dumplings',
    source: 'local',
    externalId: 'kz-manty',
    kcalPer100g: 218,
    proteinPer100g: 10.4,
    fatPer100g: 9.8,
    carbsPer100g: 22.6,
    defaultPortionG: 90,
    portionLabelRu: 'штука',
    portionLabelKk: 'дана',
    isVerified: false,
  },
  {
    nameRu: 'Самса',
    nameKk: 'Самса',
    nameEn: 'samsa meat pastry',
    source: 'local',
    externalId: 'kz-samsa',
    kcalPer100g: 296,
    proteinPer100g: 10.2,
    fatPer100g: 17.5,
    carbsPer100g: 25.4,
    defaultPortionG: 120,
    portionLabelRu: 'штука',
    portionLabelKk: 'дана',
    isVerified: false,
  },
  {
    nameRu: 'Лагман',
    nameKk: 'Лағман',
    nameEn: 'lagman noodle soup',
    source: 'local',
    externalId: 'kz-lagman',
    kcalPer100g: 142,
    proteinPer100g: 7.1,
    fatPer100g: 6.4,
    carbsPer100g: 14.2,
    defaultPortionG: 400,
    portionLabelRu: 'порция',
    portionLabelKk: 'бір порция',
    isVerified: false,
  },
  {
    nameRu: 'Плов',
    nameKk: 'Палау',
    nameEn: 'plov pilaf',
    source: 'local',
    externalId: 'kz-plov',
    kcalPer100g: 212,
    proteinPer100g: 8.2,
    fatPer100g: 8.6,
    carbsPer100g: 25.8,
    defaultPortionG: 300,
    portionLabelRu: 'порция',
    portionLabelKk: 'бір порция',
    isVerified: false,
  },
  {
    nameRu: 'Тандырная лепёшка',
    nameKk: 'Тандыр нан',
    nameEn: 'tandyr flatbread',
    source: 'local',
    externalId: 'kz-tandyr-nan',
    kcalPer100g: 265,
    proteinPer100g: 8.4,
    fatPer100g: 3.2,
    carbsPer100g: 51.2,
    defaultPortionG: 80,
    portionLabelRu: 'кусок',
    portionLabelKk: 'тілім',
    isVerified: false,
  },

  /* ────────────────── Молочные продукты ─────────────────────── */
  {
    nameRu: 'Курт',
    nameKk: 'Құрт',
    nameEn: 'kurt dried cheese',
    source: 'local',
    externalId: 'kz-kurt',
    kcalPer100g: 258,
    proteinPer100g: 25.4,
    fatPer100g: 12.8,
    carbsPer100g: 11.6,
    defaultPortionG: 25,
    portionLabelRu: 'несколько шариков',
    portionLabelKk: 'бірнеше дана',
    isVerified: false,
  },
  {
    nameRu: 'Айран',
    nameKk: 'Айран',
    nameEn: 'ayran fermented milk',
    source: 'local',
    externalId: 'kz-ayran',
    kcalPer100g: 56,
    proteinPer100g: 3.0,
    fatPer100g: 3.2,
    carbsPer100g: 4.1,
    defaultPortionG: 250,
    portionLabelRu: 'стакан',
    portionLabelKk: 'стақан',
    isVerified: false,
  },
  {
    nameRu: 'Шубат',
    nameKk: 'Шұбат',
    nameEn: 'shubat camel milk',
    source: 'local',
    externalId: 'kz-shubat',
    kcalPer100g: 62,
    proteinPer100g: 3.4,
    fatPer100g: 3.6,
    carbsPer100g: 4.4,
    defaultPortionG: 250,
    portionLabelRu: 'пиала',
    portionLabelKk: 'кесе',
    isVerified: false,
  },
  {
    nameRu: 'Кумыс',
    nameKk: 'Қымыз',
    nameEn: 'kumys mare milk',
    source: 'local',
    externalId: 'kz-kumys',
    kcalPer100g: 50,
    proteinPer100g: 2.1,
    fatPer100g: 1.9,
    carbsPer100g: 5.0,
    defaultPortionG: 250,
    portionLabelRu: 'пиала',
    portionLabelKk: 'кесе',
    isVerified: false,
  },
  {
    nameRu: 'Иримшик',
    nameKk: 'Ірімшік',
    nameEn: 'irimshik cheese',
    source: 'local',
    externalId: 'kz-irimshik',
    kcalPer100g: 332,
    proteinPer100g: 29.5,
    fatPer100g: 20.4,
    carbsPer100g: 8.2,
    defaultPortionG: 40,
    portionLabelRu: 'горсть',
    portionLabelKk: 'уыс',
    isVerified: false,
  },
  {
    nameRu: 'Сарымай (топлёное масло)',
    nameKk: 'Сарымай',
    nameEn: 'clarified butter ghee',
    source: 'local',
    externalId: 'kz-sarymai',
    kcalPer100g: 892,
    proteinPer100g: 0.3,
    fatPer100g: 99.0,
    carbsPer100g: 0,
    defaultPortionG: 10,
    portionLabelRu: 'чайная ложка',
    portionLabelKk: 'шай қасық',
    isVerified: false,
  },

  /* ──────────────────── Сладкое и чай ───────────────────────── */
  {
    nameRu: 'Жент',
    nameKk: 'Жент',
    nameEn: 'zhent millet sweet',
    source: 'local',
    externalId: 'kz-zhent',
    kcalPer100g: 448,
    proteinPer100g: 8.1,
    fatPer100g: 24.6,
    carbsPer100g: 49.2,
    defaultPortionG: 30,
    portionLabelRu: 'кусочек',
    portionLabelKk: 'тілім',
    isVerified: false,
  },
  {
    nameRu: 'Чай с молоком',
    nameKk: 'Сүтті шай',
    nameEn: 'milk tea',
    source: 'local',
    externalId: 'kz-milk-tea',
    kcalPer100g: 38,
    proteinPer100g: 1.6,
    fatPer100g: 1.9,
    carbsPer100g: 3.6,
    defaultPortionG: 200,
    portionLabelRu: 'пиала',
    portionLabelKk: 'кесе',
    isVerified: false,
  },
  {
    nameRu: 'Талкан',
    nameKk: 'Талқан',
    nameEn: 'talkan roasted grain',
    source: 'local',
    externalId: 'kz-talkan',
    kcalPer100g: 385,
    proteinPer100g: 11.2,
    fatPer100g: 4.8,
    carbsPer100g: 74.5,
    defaultPortionG: 40,
    portionLabelRu: 'горсть',
    portionLabelKk: 'уыс',
    isVerified: false,
  },
];
